version: '3.7'
services:

    sabinus_service_server:
        container_name: sabinus_service_server
        build:
            context: ./docker/local
            dockerfile: ./nginx/Dockerfile
        restart: unless-stopped
        ports:
            - ${ENV_SERVICE_SERVER_PORT}:80
        volumes:
            - ./:/var/www/html
            - ./docker/local/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - sabinus_service_network

    sabinus_redis:
        container_name: sabinus_redis
        image: redis:6
        restart: always
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}
        command: --port ${REDIS_PORT}
        expose:
            - ${REDIS_PORT}
        volumes:
            - ./data:/data
        networks:
            - sabinus_service_network

    redis-commander:
        image: rediscommander/redis-commander:latest
        environment:
            - REDIS_HOSTS=sabinus_service_network:sabinus_redis:${REDIS_PORT}
        ports:
            - ${REDIS_UI_PORT}:8081
        networks:
            - sabinus_service_network
        depends_on:
            - sabinus_redis

    sabinus_service_api:
        container_name: sabinus_service_api
        build:
            context: ./
            dockerfile: ./docker/local/php/Dockerfile
        ports:
            - ${ENV_SERVICE_API_PORT}:${ENV_SERVICE_API_PORT}
        volumes:
            - ./:/var/www/html
        networks:
            - sabinus_service_network
        depends_on:
            - sabinus_redis
            - sabinus_service_server

networks:
    sabinus_service_network:
        name: sabinus_service_network
    cache:
        driver: local